version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - sam-local
    ports:
      - "8000:8000"

networks:
  sam-local:
    external: true
