services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   network_mode: "host"
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - "./docker/dynamodb:/home/dynamodblocal/data"
  #  working_dir: /home/dynamodblocal